CC=    gcc
CXX=   g++
LD=    g++

CFLAGS= -O2 -mssse3 -mpclmul -std=gnu99 -Wall -Wextra
CXXFLAGS= -O2 -mssse3 -mpclmul -Wall -Wextra
#CXXFLAGS= -O2 -mssse3 -mpclmul -Wall -Wextra -fno-exceptions -fno-rtti
INCPATH= -I/usr/local/include -I/opt/local/include -I/usr/include -I../
LDFLAGS= 
LIBPATH= -L/usr/local/lib -L/opt/local/lib -L/usr/lib
LIBS=    -lm -lcrypto
#LIBS=    -lm -lcrypto -lstdc++
OBJ= $(wildcard ../*.o)


TAR= quartz-test quartz-benchmark-test gf2ext_poly-test

CSRC= $(wildcard *.cpp)


ifndef QUARTZ
        QUARTZ1= QUARTZ96
else
	QUARTZ1= $(QUARTZ)
endif
        CFLAGS += -D$(QUARTZ1)
        CXXFLAGS += -D$(QUARTZ1)



ifdef HFE
        CFLAGS+=  -DHFE2
        CXXFLAGS+= -DHFE2
endif
	

ifdef DEBUG
        CFLAGS+=  -D_DEBUG_
        CXXFLAGS+= -D_DEBUG_
endif

ifdef NO_SSE
	CFLAGS += -D_NO_SSE_
	CXXFLAGS += -D_NO_SSE_
endif

ifdef AVX2
	CFLAGS += -mavx2 -D_USE_AVX2_
	CXXFLAGS += -mavx2 -D_USE_AVX2_
endif

ifdef AVX
	CFLAGS += -mavx -D_USE_AVX_
	CXXFLAGS += -mavx -D_USE_AVX_
endif

ifdef GPROF
	CFLAGS += -pg
	CXXFLAGS += -pg
	LDFLAGS += -pg
endif

.PHONY: all tests tables clean

all: $(TAR)
#$(OBJ)

#%-test: $(OBJ) %-test.o
%-test: %-test.o
	$(LD) $(LDFLAGS) $(LIBPATH) $(OBJ) -o $@ $^ $(LIBS)

%.o: %.c
	$(CC) $(CFLAGS) $(INCPATH) -c $<

%.o: %.cpp
	$(CXX) $(CXXFLAGS) $(INCPATH) -c $<

clean:
	rm *.o; rm *-test
