#ifndef _RUN_CONFIG_H_
#define _RUN_CONFIG_H_

//#define CONFIG_SSE_VEC

#define CONFIG_HAS_PCLMULQDQ

#define CONFIG_FAST_PCLMULQDQ

#define CONFIG_PCLMULQDQ_REDUCE

//#define CONFIG_PROFILE

//#define CONFIG_PSHUFB

//#define _NO_OPENSSL_

//#define CONFIG_BENCH_SYSTIME

//#define CONFIG_NEON

#endif /// _RUN_CONFIG_H_
